---
- hosts: all
  become: yes
  roles:
    - geerlingguy.docker
  tasks:
    - name: ensure a list of packages installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - python-pip
          - python-setuptools
    - name: install virtualenv
      pip:
        name:
          - virtualenv
    - name: Install docker-py
      pip:
        name: docker
        state: present
    - name: Restart a container
      docker_container:
        name: mariadb
        image: mariadb:10.2
        state: started
        # restart: yes
        restart_policy: always
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
